### ISSUE TITLE
Elective Courses

### ISSUE THREAD

**Issue by pohlm01** [pblan/matse-stundenplan#2]
Would it be possible to also add a calendar for the elective courses? Actually I don't know how to do this the best, because having all the courses in one calendar wouldn't be to helpful, but creating one calendar for each course would cause maintenance work and isn't very clear. Maybe you have any ideas how to implement this?

**Comment by pblan** [comment]
Hi! That is in fact on my to-do list. The approach I am thinking about is to let users specify what they would like to see - e.g. first year and C++ - and then generate a file based on that. Brainstorming is not yet finished, but I am thinking about it. :)

**Comment by pblan** [comment]
@pohlm01 Done! You can find more information on how to use the calendar with personal elective courses on https://paddel.xyz/matse !

Please contact me if there are further questions!

**Comment by pblan** [comment]
Issue closed.
